import type { SkillDefinitionDetail } from '../../types/skill'

const DEFAULT_ANTHROPIC_MODEL = process.env.SKILL_ANTHROPIC_DEFAULT_MODEL?.trim() || 'anthropic-default'
const CREATED_AT = '2026-04-25T00:00:00.000Z'

export const DEFAULT_SKILL_DEFINITIONS: SkillDefinitionDetail[] = [
  {
    slug: 'learning-topic-generator',
    name: '学习主题拆解',
    description: '围绕书籍、概念或技能主题生成结构化学习路径，并为后续内容写入预留工作流入口。',
    category: 'workflow',
    engine_type: 'llm_direct',
    source_type: 'inline',
    source_path: null,
    source_origin: 'builtin',
    source_label: 'Built-in',
    source_version: 'seed-2026-04-25',
    source_metadata: {},
    input_schema: {
      type: 'object',
      required: ['topic', 'source_type'],
      properties: {
        topic: { type: 'string', title: '学习主题' },
        source_type: { type: 'string', enum: ['book', 'concept', 'skill'], title: '主题类型' },
        depth: { type: 'string', enum: ['brief', 'standard', 'deep'], title: '生成深度' },
        context: { type: 'string', title: '补充上下文' },
      },
    },
    output_schema: {
      type: 'object',
      properties: {
        slug: { type: 'string' },
        total_chapters: { type: 'number' },
        estimated_read_minutes: { type: 'number' },
      },
    },
    default_provider: 'anthropic',
    default_model: DEFAULT_ANTHROPIC_MODEL,
    tool_policy: {
      network: true,
      filesystem_read: true,
      filesystem_write: true,
      shell: false,
      browser: false,
      approval_required: true,
    },
    status: 'active',
    created_at: CREATED_AT,
    updated_at: CREATED_AT,
  },
  {
    slug: 'article-summary-polisher',
    name: '文章摘要润色',
    description: '对已有正文或摘要进行压缩、提炼和重写，输出适合归档或展示的 Markdown 摘要。',
    category: 'prompt',
    engine_type: 'llm_direct',
    source_type: 'inline',
    source_path: null,
    source_origin: 'builtin',
    source_label: 'Built-in',
    source_version: 'seed-2026-04-25',
    source_metadata: {},
    input_schema: {
      type: 'object',
      required: ['content'],
      properties: {
        title: { type: 'string', title: '标题' },
        content: { type: 'string', title: '正文' },
        tone: { type: 'string', enum: ['neutral', 'technical', 'brief'], title: '语气' },
      },
    },
    output_schema: {
      type: 'object',
      properties: {
        summary: { type: 'string' },
        bullets: { type: 'array', items: { type: 'string' } },
      },
    },
    default_provider: 'anthropic',
    default_model: DEFAULT_ANTHROPIC_MODEL,
    tool_policy: {
      network: false,
      filesystem_read: false,
      filesystem_write: false,
      shell: false,
      browser: false,
      approval_required: false,
    },
    status: 'active',
    created_at: CREATED_AT,
    updated_at: CREATED_AT,
  },
  {
    slug: 'daily-ai-briefing',
    name: '每日 AI 简报',
    description: '基于主题、日期和补充来源线索生成一版 AI 日报草稿，当前采用托管式多步 workflow runner。',
    category: 'workflow',
    engine_type: 'agent_sdk',
    source_type: 'inline',
    source_path: null,
    source_origin: 'builtin',
    source_label: 'Built-in',
    source_version: 'seed-2026-04-25',
    source_metadata: {},
    input_schema: {
      type: 'object',
      required: ['date', 'topic'],
      properties: {
        date: { type: 'string', title: '日期' },
        topic: { type: 'string', title: '主题' },
        locale: { type: 'string', title: '语言/区域' },
        audience: { type: 'string', title: '目标读者' },
        source_notes: { type: 'string', title: '补充来源线索' },
      },
    },
    output_schema: {
      type: 'object',
      properties: {
        markdown: { type: 'string' },
        items_count: { type: 'number' },
      },
    },
    default_provider: 'anthropic',
    default_model: DEFAULT_ANTHROPIC_MODEL,
    tool_policy: {
      network: true,
      filesystem_read: false,
      filesystem_write: true,
      shell: false,
      browser: false,
      approval_required: true,
    },
    status: 'active',
    created_at: CREATED_AT,
    updated_at: CREATED_AT,
  },
]
